"""
pdf_builder.py

This module is responsible for generating searchable PDF files from OCR output.

The primary goal is to preserve the original visual appearance of scanned
documents while embedding an invisible text layer produced by OCR engines
(Tesseract, Vision LLMs, or combined OCR workflows).

Planned functionality:

- Create searchable PDFs from scanned image PDFs.
- Preserve original page images, layout, and formatting.
- Embed invisible OCR text behind each page image.
- Support OCR text generated by multiple engines.
- Export PDFs that remain searchable in:
    - Zotero
    - DEVONthink
    - Adobe Acrobat
    - Preview (macOS)
    - Other PDF readers
- Optionally store OCR metadata (engine used, confidence scores, etc.).
- Serve as the final output stage of the OCR pipeline after text extraction
  and page-level OCR processing have been completed.

Typical workflow:

    Original Scan PDF
            ↓
       OCR Pipeline
            ↓
      OCR Text Output
            ↓
    build_searchable_pdf()
            ↓
     Searchable PDF File

This module does not perform OCR itself. It only constructs PDF outputs using OCR text that has already been generated elsewhere in the system.
"""